// <auto-generated />
using System;
using LoR.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260821185341_AddItemTables")]
    partial class AddItemTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("server.Models.ItemModels.Affix", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AffixCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AffixType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxValue")
                        .HasColumnType("integer");

                    b.Property<int>("MinValue")
                        .HasColumnType("integer");

                    b.Property<string>("ModifierType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Affixs");
                });

            modelBuilder.Entity("server.Models.ItemModels.BaseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsUnique")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemSubType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumSlots")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BaseItems");
                });

            modelBuilder.Entity("server.Models.ItemModels.BaseItemAffixPool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AffixId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaseItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AffixId");

                    b.HasIndex("BaseItemId");

                    b.ToTable("BaseItemAffixPool");
                });

            modelBuilder.Entity("server.Models.ItemModels.BaseItemModifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaseItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModifierType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BaseItemId");

                    b.ToTable("BaseItemModifiers");
                });

            modelBuilder.Entity("server.Models.ItemModels.ItemInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaseItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BaseItemId");

                    b.ToTable("ItemInstances");
                });

            modelBuilder.Entity("server.Models.ItemModels.ItemInstanceAffix", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AffixId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemInstanceId")
                        .HasColumnType("uuid");

                    b.Property<int>("RolledValue")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AffixId");

                    b.HasIndex("ItemInstanceId");

                    b.ToTable("ItemInstanceAffixes");
                });

            modelBuilder.Entity("server.Models.ItemModels.BaseItemAffixPool", b =>
                {
                    b.HasOne("server.Models.ItemModels.Affix", "Affix")
                        .WithMany()
                        .HasForeignKey("AffixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.ItemModels.BaseItem", "BaseItem")
                        .WithMany()
                        .HasForeignKey("BaseItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Affix");

                    b.Navigation("BaseItem");
                });

            modelBuilder.Entity("server.Models.ItemModels.BaseItemModifier", b =>
                {
                    b.HasOne("server.Models.ItemModels.BaseItem", "BaseItem")
                        .WithMany()
                        .HasForeignKey("BaseItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseItem");
                });

            modelBuilder.Entity("server.Models.ItemModels.ItemInstance", b =>
                {
                    b.HasOne("server.Models.ItemModels.BaseItem", "BaseItem")
                        .WithMany()
                        .HasForeignKey("BaseItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseItem");
                });

            modelBuilder.Entity("server.Models.ItemModels.ItemInstanceAffix", b =>
                {
                    b.HasOne("server.Models.ItemModels.Affix", "Affix")
                        .WithMany()
                        .HasForeignKey("AffixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.ItemModels.ItemInstance", "ItemInstance")
                        .WithMany()
                        .HasForeignKey("ItemInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Affix");

                    b.Navigation("ItemInstance");
                });
#pragma warning restore 612, 618
        }
    }
}
